chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
chrome_extra_args = "--user-data-dir=/Users/singhpra/Documents/ChromeDataDir"

[scanner_config]
"Market Cap" = "500M"
"Stock Price" = "12"
"Average Volume" = "500K"
"Average True Range (ATR)" = "1.5"
"Sector" = ""
"Industry" = ""
"Exchange" = ""

[period_config]
"Price Change 1M" = 20
"Price Change 3M" = 35
"Price Change 6M" = 50
"Price Change 1Y" = 100


[sector_etfs]
"Communication Services" = "AMEX:XLC"
"Consumer Discretionary" = "AMEX:XLY"
"Consumer Staples" = "AMEX:XLP"
"Energy" = "AMEX:XLE"
"Financials" = "AMEX:XLF"
"Healthcare" = "AMEX:XLV"
"Industrials" = "AMEX:XLI"
"Materials" = "AMEX:XLB"
"Real Estate" = "AMEX:XLRE"
"Technology" = "AMEX:XLK"
"Utilities" = "AMEX:XLU"

[industry_etfs]
"Advertising Agencies" = "CBOE:IYZ"
"Aerospace & Defense" = "CBOE:ITA"
"Asset Management - Cryptocurrency" = "AMEX:IBLC"
"Auto & Truck Dealerships" = "AMEX:IYC"
"Auto Manufacturers" = "AMEX:IYC"
"Auto Parts" = "AMEX:IYC"
"Beverages - Non-Alcoholic" = "AMEX:IYK"
"Biotechnology" = "NASDAQ:IBB"
"Building Products & Equipment" = "CBOE:ITB"
"Capital Markets" = "AMEX:IAI"
"Coking Coal" = "CBOE:PICK"
"Communication Equipment" = "CBOE:IYZ"
"Computer Hardware" = "AMEX:IYW"
"Consulting Services" = "CBOE:IYJ"
"Copper" = "CBOE:PICK"
"Credit Services" = "AMEX:IYG"
"Diagnostics & Research" = "AMEX:IHF"
"Drug Manufacturers - Specialty & Generic" = "AMEX:IHE"
"Electrical Equipment & Parts" = "CBOE:IYJ"
"Electronic Components" = "AMEX:IYW"
"Electronic Gaming & Multimedia" = "CBOE:IYZ"
"Engineering & Construction" = "CBOE:IFRA"
"Entertainment" = "CBOE:IYZ"
"Farm & Heavy Construction Machinery" = "CBOE:IYJ"
"Financial Data & Stock Exchanges" = "AMEX:IAI"
"Footwear & Accessories" = "AMEX:IYC"
"Gold" = "AMEX:IAU"
"Health Information Services" = "AMEX:IYH"
"Household & Personal Products" = "AMEX:IYK"
"Information Technology Services" = "AMEX:IYW"
"Insurance - Property & Casualty" = "AMEX:IAK"
"Integrated Freight & Logistics" = "CBOE:IYT"
"Internet Content & Information" = "CBOE:IYZ"
"Internet Retail" = "AMEX:IYC"
"Luxury Goods" = "AMEX:IYC"
"Medical Devices" = "AMEX:IHI"
"Medical Instruments & Supplies" = "AMEX:IHI"
"Metal Fabrication" = "CBOE:IYJ"
"Mortgage Finance" = "AMEX:IYG"
"Oil & Gas Equipment & Services" = "AMEX:IEZ"
"Oil & Gas Midstream" = "AMEX:IYE"
"Oil & Gas Refining & Marketing" = "AMEX:IYE"
"Other Industrial Metals & Mining" = "CBOE:PICK"
"Personal Services" = "AMEX:IYC"
"Pollution & Treatment Controls" = "NASDAQ:ICLN"
"Recreational Vehicles" = "AMEX:IYC"
"Rental & Leasing Services" = "CBOE:IYJ"
"Resorts & Casinos" = "AMEX:IYC"
"Scientific & Technical Instruments" = "AMEX:IYW"
"Semiconductor Equipment & Materials" = "NASDAQ:SOXX"
"Semiconductors" = "NASDAQ:SOXX"
"Software - Application" = "CBOE:IGV"
"Software - Infrastructure" = "CBOE:IGV"
"Solar" = "NASDAQ:ICLN"
"Specialty Business Services" = "CBOE:IYJ"
"Specialty Industrial Machinery" = "CBOE:IYJ"
"Specialty Retail" = "AMEX:IYC"
"Telecom Services" = "CBOE:IYZ"
"Thermal Coal" = "CBOE:PICK"
"Uranium" = "CBOE:PICK"
"Utilities - Independent Power Producers" = "AMEX:IDU"
"Utilities - Regulated Electric" = "AMEX:IDU"
"Utilities - Renewable" = "NASDAQ:ICLN"
