# chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
# chrome_extra_args = "--user-data-dir=/Users/singhpra/Documents/ChromeDataDir"

chrome_path = "/opt/google/chrome/chrome"
chrome_extra_args = "--user-data-dir=/home/prashant/OptionsMaker/chrome_data"

fetch_pages = 10
period_config = [
    "Price Change 1M",
    "Price Change 3M",
    "Price Change 6M",
    "Price Change 1Y",
]

fetch_fundamentals = false

[scanner_config]
"Market Cap" = "500M"
"Stock Price" = "12"
"Average Volume" = "500K"
"Average True Range (ATR)" = "1.5"
"Sector" = ""
"Industry" = ""
"Exchange" = ""
