[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }

rustls = "0.23"
time = { version = "0.3", features = ["macros"] }

tracing-subscriber = { version = "0", features = ["env-filter", "local-time"] }
tracing = { workspace = true }
mimalloc = "0.1"

app_config = { path = "../app_config" }
schwab_client = { path = "../schwab_client" }

tokio = { workspace = true, features = ["full"] }
axum = { version = "0.8", features = ["ws"] }


persist = { path = "../persist" }