services:
  postgres_dev:
    image: postgres:17
    restart: no
    ports:
      - 5432:5432
    volumes:
      - dev_db_data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  dev_db_data:
